---
# a blue-green deployment of the boilerplate
version: '3.7'

services:
  blue-green-proxy:
    image: nginx:1.18-alpine
    container_name: blue-green-proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend
    ports:
      - 80:80

  blue:
    image: nodejs-boilerplate:0.0.0
    container_name: blue
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8080
      - LOG_LEVEL=info
    networks:
      - frontend
      - backend

  green:
    image: nodejs-boilerplate:0.0.0
    container_name: green
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8080
      - LOG_LEVEL=info
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: frontend
  backend:
    name: backend
